package org.cross.medicore.shared;

public enum Action {
    READ_PATIENT_DETAILS,
    MODIFY_PATIENT_DETAILS,
    SCHEDULE_APPOINTMENT,
    BEGIN_ENCOUNTER,
    END_ENCOUNTER,
    CANCEL_APPOINTMENT,
    MODIFY_PRESCRIPTION,
    MODIFY_VITALS,
    ADD_PROVIDER,
    ADD_PROVIDER_SCHEDULE,
    READ_ENCOUNTER_DETAILS
}
